### ISSUE TITLE
Test failure - thread 'misc::escape' panicked at /usr/src/RPM/BUILD/argc-1.21.1/vendor/insta/src/runtime.rs:680:13:

### ISSUE THREAD

**Issue by vt-alt** [sigoden/argc#353]
I try to build `argc` package for ALT, but there's test failure (for the head of `main` branch):
```
01:40:31 + cargo test --release
...
01:41:34      Running `/usr/src/RPM/BUILD/argc-1.21.1/target/release/deps/integration-f7bc15118574750c`
01:41:34
01:41:34 running 205 tests
...
01:41:34 test validate::require_tools ... ok
01:41:34 test spec::arg_eval ... ok
01:41:34 test spec::option_help ... ok
01:41:34 test spec::option_eval ... ok
01:41:34 test spec::arg_subcmd_help ... ok
01:41:36 test cli::parallel ... ok
01:41:36
01:41:36 failures:
01:41:36
01:41:36 ---- misc::escape stdout ----
01:41:36 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
01:41:36 Snapshot file: tests/snapshots/integration__misc__escape.snap
01:41:36 Snapshot: escape
01:41:36 Source: tests/misc.rs:5
01:41:36 ────────────────────────────────────────────────────────────────────────────────
01:41:36 Expression: data
01:41:36 ────────────────────────────────────────────────────────────────────────────────
01:41:36 -old snapshot
01:41:36 +new results
01:41:36 ────────────┬───────────────────────────────────────────────────────────────────
01:41:36    10    10 │ cmd '$foo' '`pwd`' '$(pwd)' ''\''' '\1' '' '
01:41:36    11    11 │ ' 世界 ' '
01:41:36    12    12 │
01:41:36    13    13 │ # BUILD_OUTPUT
01:41:36    14       │-argc__args=([0]="prog" [1]="cmd" [2]="\$foo" [3]="\`pwd\`" [4]="\$(pwd)" [5]="'" [6]="\\1" [7]="" [8]=$'\n' [9]="世界" [10]=" ")
01:41:36          14 │+argc__args=([0]="prog" [1]="cmd" [2]="\$foo" [3]="\`pwd\`" [4]="\$(pwd)" [5]="'" [6]="\\1" [7]="" [8]=$'\n' [9]=$'\344\270\226\347\225\214' [10]=" ")
01:41:36    15    15 │ argc__fn=cmd
01:41:36    16       │-argc__positionals=([0]="\$foo" [1]="\`pwd\`" [2]="\$(pwd)" [3]="'" [4]="\\1" [5]="" [6]=$'\n' [7]="世界" [8]=" ")
01:41:36          16 │+argc__positionals=([0]="\$foo" [1]="\`pwd\`" [2]="\$(pwd)" [3]="'" [4]="\\1" [5]="" [6]=$'\n' [7]=$'\344\270\226\347\225\214' [8]=" ")
01:41:36    17    17 │ cmd $foo `pwd` $(pwd) ' \1
01:41:36    18    18 │  世界
01:41:36 ────────────┴───────────────────────────────────────────────────────────────────
01:41:36 To update snapshots run `cargo insta review`
01:41:36 Stopped on the first failure. Run `cargo insta test` to run all snapshots.
01:41:36 thread 'misc::escape' panicked at /usr/src/RPM/BUILD/argc-1.21.1/vendor/insta/src/runtime.rs:680:13:
01:41:36 snapshot assertion for 'escape' failed in line 5
01:41:36 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
01:41:36
01:41:36
01:41:36 failures:
01:41:36     misc::escape
01:41:36
01:41:36 test result: FAILED. 204 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.05s
01:41:36
01:41:36 error: test failed, to rerun pass `--test integration`
01:41:36 error: Bad exit status from /usr/src/tmp/rpm-tmp.14454 (%check)
```
The build and tests are run in clean environment.
```
01:47:07 + locale
01:47:07 LANG=
01:47:07 LC_CTYPE="POSIX"
01:47:07 LC_NUMERIC="POSIX"
01:47:07 LC_TIME="POSIX"
01:47:07 LC_COLLATE="POSIX"
01:47:07 LC_MONETARY="POSIX"
01:47:07 LC_MESSAGES="POSIX"
01:47:07 LC_PAPER="POSIX"
01:47:07 LC_NAME="POSIX"
01:47:07 LC_ADDRESS="POSIX"
01:47:07 LC_TELEPHONE="POSIX"
01:47:07 LC_MEASUREMENT="POSIX"
01:47:07 LC_IDENTIFICATION="POSIX"
01:47:07 LC_ALL=
```
```
builder@x86_64:/.in$ cargo -V
cargo 1.82.0 (8f40fc59f 2024-08-21)
builder@x86_64:/.in$ rustc -V
rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball)
```

**Comment by sigoden** [comment]
@vt-alt 

Setting `LANG` to `C.UTF-8` or `en_US.UTF-8` should solve the problem.

**Comment by vt-alt** [comment]
Yes this helped, thank you!
